---
title: "Tables and Figures for Manuscript"
author: "Inna Cohen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include=T, message=F)

library(data.table)
library(tidyverse)
library(table1)
library(officer)
library(flextable)


master = fread("/gpfs/milgram/project/rtaylor/imc33/LOS/data/master_los.csv")


# Concise output for followup table (only Yes's, instead of Yes/No)
rndr <- function(x, ...) {
  y <- render.default(x, ...)
  if (is.logical(x)) y[2] else y
}


#Show the mean (SD) and median (IQR) for continuous variables
my.render.cont <- function(x) {
  with(stats.default(x), 
       c("",
         
         "Mean (SD)" = sprintf("%s (%s)",
                               round_pad(MEAN, 1),
                               round_pad(SD, 1)),
         
         "Median (IQR)" = sprintf("%s (%s, %s)",
                                  round_pad(MEDIAN, 1), 
                                  round_pad(Q1, 1), 
                                  round_pad(Q3, 1)))
  )}


t2flex <- function(df){
  t1flex(df) %>% 
    autofit() %>%
    fit_to_width(10)}

#ref:https://stackoverflow.com/questions/49150272/exporting-several-tables-to-word-documents-using-r-package-flextable
write_word_table <- function(var, doc){
  doc %>%
    body_add_flextable(var) %>% 
    body_add_break() }

map_drg <- function(value) {
  dplyr::case_when(
    value %in% c("Bronchitis & asthma w cc/mcc",
                 "Respiratory infections & inflammations w mcc",
                 "Simple pneumonia & pleurisy w mcc") ~ "Respiratory Infections (CC/MCC)",
    
    value == "Cellulitis w/o mcc" ~ "Cellulitis (No MCC)",
    
    value == "Circulatory disorders except ami, w card cath w mcc" ~ "Circulatory disorders (MCC)",
    
    value == "Craniotomy & endovascular intracranial procedures w mcc" ~ "Craniotomy/Intracranial Procedures (MCC)",
    
    value == "Degenerative nervous system disorders w/o mcc" ~ "Neurological Disorders (No MCC)",
    
    value == "Diabetes w cc" ~ "Diabetes (CC)",
    
    value %in% c("Esophagitis, gastroent & misc digest disorders w mcc",
                 "Esophagitis, gastroent & misc digest disorders w/o mcc") ~ "GI Disorders (MCC/No MCC)",
    
    value %in% c("G.i. hemorrhage w cc", "G.i. hemorrhage w mcc") ~ "GI Hemorrhage (CC/MCC)",
    
    value %in% c("heart failure & shock w mcc", 
                "percut cardiovasc proc w drug-eluting stent w mcc or 4+ arteries/stents (retired fy 2024)") ~ "Heart/Respiratory Failure (MCC)",
    
    value == "Hip & femur procedures except major joint w cc" ~ "Hip/Femur Procedures (CC)",
    
    value %in% c("Infectious & parasitic diseases w o.r. procedure w mcc",
                 "Septicemia or severe sepsis w/o mv >96 hours w/o mcc",
                 "Septicemia or severe sepsis w/o mv >96 hours w mcc") ~ "Sepsis & Severe Infections (MCC/No MCC)",
    
    value == "Intracranial hemorrhage or cerebral infarction w mcc" ~ "Intracranial Hemorrhage (MCC)",
    
    value %in% c("Kidney & urinary tract infections w mcc",
                 "Kidney & urinary tract infections w/o mcc",
                 "Other kidney & urinary tract diagnoses w mcc") ~ "UTI (MCC/No MCC)",
    
    value %in% c("Misc disorders of nutrition,metabolism,fluids/electrolytes w mcc",
                 "Misc disorders of nutrition,metabolism,fluids/electrolytes w/o mcc") ~ "Metabolic Disorders (MCC/No MCC)",
    
    value == "Percut cardiovasc proc w drug-eluting stent w mcc or 4+ arteries/stents (retired fy 2024)" ~ "Cardiovascular Stent Procedure (MCC)",
    
    value == "Poisoning & toxic effects of drugs w mcc" ~ "Drug Poisoning (MCC)",
    
    value == "Red blood cell disorders w/o mcc" ~ "RBC Disorders (No MCC)",
    
    value == "Renal failure w mcc" ~ "Renal Failure (MCC)",
    
    value %in% c("Seizures w mcc", "Seizures w/o mcc") ~ "Seizures (MCC/No MCC)",
    
    TRUE ~ as.character(value)  # Keep other values unchanged
  )
}
```

### Cohort Characteristics


```{r}
master = master %>%
  mutate(viz_drg = map_drg(viz_drg))

  
top5_drg = master %>%
  group_by(viz_drg) %>%
  count() %>%
  arrange(desc(n)) %>%
  head(5) %>%
  pull(viz_drg)


master = master %>%
  mutate(
     icu_any_icu_yn = factor(icu_any_icu_yn, levels=c(1,0), labels=c("ICU","Non-ICU")),
     viz_outcome_prolonged_los_yn = factor(viz_outcome_prolonged_los_yn, levels=c(1,0), labels = c("Prolonged LOS", "Reduced LOS")),
     top5_drgs = ifelse(viz_drg %in% top5_drg, viz_drg, "Other"),
     thro_boarding_yn = factor(thro_boarding_yn, levels=c(1,0), labels=c("ED Boarders","Non-Boarders"))
     
)


label(master$viz_age) = "Age"
label(master$viz_gender) = "Gender"
label(master$viz_race) = "Race"
label(master$viz_ethnicity) = "Ethnicity"
label(master$viz_language) = "Language"
label(master$viz_insurance) = "Insurance"
label(master$viz_service_collapsed) = "Service"
label(master$viz_disp_collapsed) = "Disposition"
label(master$viz_outcome_prolonged_los_yn) = "O:E Ratio"
label(master$icu_any_icu_yn) = "ICU"    
label(master$top5_drgs) = "Top DRGS"
label(master$thro_boarding_yn) = "Boarding Status"



t1 = table1(~viz_age + viz_gender + viz_race + viz_ethnicity + viz_language + viz_insurance + viz_service_collapsed + viz_disp_collapsed + icu_any_icu_yn + top5_drgs + thro_boarding_yn | viz_outcome_prolonged_los_yn, data=master , render = rndr,  render.continuous = my.render.cont, caption = "Table 1. Overall")

t1
```
                                             

```{r}
master %>%
  names()
```



### Consult and Imaging data

```{r}

label(master$con_max_admit_order_to_consult_order_any_hrs) = "Admit Order to Consult Order (hours)"
label(master$con_max_consult_order_to_note_any_hrs) = "Consult order to Note (hours)"
label(master$con_max_consult_order_to_sign_any_hrs) = "Consult Order to Sign (hours)"
label(master$con_max_admit_order_to_consult_completion_any_hrs) = "Admit Order to Consult Completion (hours)"
label(master$img_max_admit_order_to_imaging_order_any_hrs) = "Admit Order to Imaging Order (hours)"
label(master$img_max_order_to_completion_any_hrs) = "Imaging Order to Completion (hours)"
label(master$img_max_order_to_read_any_hrs) = "Imaging Order to Read (hours)"
label(master$img_max_admit_order_to_imaging_read_any_hrs) = "Admit Order to Imaging Read (hours)"



s2 = master %>%
  drop_na(thro_boarding_yn) %>%
            table1(~con_max_admit_order_to_consult_order_any_hrs +
              con_max_consult_order_to_sign_any_hrs + 
              con_max_admit_order_to_consult_completion_any_hrs +
              img_max_admit_order_to_imaging_order_any_hrs + img_max_order_to_completion_any_hrs +
              img_max_order_to_read_any_hrs +
              img_max_admit_order_to_imaging_read_any_hrs | thro_boarding_yn, data=., overall=F)

s2
```

### DRG numbers (%) stratified by OE and Total (similar to table)


```{r}
label(master$viz_drg) = "DRG"


s3 = table1(~viz_drg|viz_outcome_prolonged_los_yn, data=master)

```

```{r}
#export results
# list of tables and the doc
my_list <- list(df3 <- t2flex(s3),
                df2 <- t2flex(s2),
                df1 <- t2flex(t1))

my_doc <- read_docx()

# use walk (the invisible function of map) to include all tables in one doc
walk(my_list, write_word_table, my_doc)

formatted_date = format(Sys.Date(), "%Y-%m-%d")
fname = paste0("../output/proage_tables_",formatted_date,".docx")
print(my_doc, target = fname) %>% invisible()

```




